from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

FOOD_ITEMS = [
    {
        "name": "Regular potato, boiled",
        "kcal_per_100g": "87.00",
        "protein_g": "1.90",
        "fat_g": "0.10",
        "carb_g": "20.10",
        "satiety_index": 323,
        "common_unit": "1 medium potato = 170g",
        "notes": "Holt satiety score for potato. Macros are for boiled potato, flesh and skin.",
    },
    {
        "name": "Sweet potato, boiled",
        "kcal_per_100g": "76.00",
        "protein_g": "1.40",
        "fat_g": "0.10",
        "carb_g": "17.70",
        "satiety_index": 260,
        "common_unit": "1 medium sweet potato = 150g",
        "notes": "Satiety score estimated from potato/root vegetable pattern.",
    },
    {
        "name": "Pumpkin, cooked",
        "kcal_per_100g": "20.00",
        "protein_g": "0.70",
        "fat_g": "0.10",
        "carb_g": "4.90",
        "satiety_index": 180,
        "common_unit": "1 cup mashed = 245g",
        "notes": "Satiety score estimated for high-volume cooked vegetable.",
    },
    {
        "name": "Brown rice, cooked",
        "kcal_per_100g": "123.00",
        "protein_g": "2.70",
        "fat_g": "1.00",
        "carb_g": "25.60",
        "satiety_index": 132,
        "common_unit": "1 cup cooked = 195g",
        "notes": "Satiety score estimated from cooked whole grains.",
    },
    {
        "name": "Sadza, cooked",
        "kcal_per_100g": "109.00",
        "protein_g": "2.40",
        "fat_g": "0.40",
        "carb_g": "23.70",
        "satiety_index": 120,
        "common_unit": "1 cup cooked = 240g",
        "notes": "Macros estimated for plain cooked maize meal. Satiety score estimated.",
    },
    {
        "name": "Brown bread",
        "kcal_per_100g": "247.00",
        "protein_g": "8.80",
        "fat_g": "3.40",
        "carb_g": "41.30",
        "satiety_index": 154,
        "common_unit": "1 slice = 35g",
        "notes": "Holt satiety score for brown bread.",
    },
    {
        "name": "Chicken breast, cooked skinless",
        "kcal_per_100g": "165.00",
        "protein_g": "31.00",
        "fat_g": "3.60",
        "carb_g": "0.00",
        "satiety_index": 210,
        "common_unit": "1 cooked breast = 170g",
        "notes": "Satiety score estimated for lean cooked poultry.",
    },
    {
        "name": "Chicken thigh, cooked skinless",
        "kcal_per_100g": "209.00",
        "protein_g": "26.00",
        "fat_g": "10.90",
        "carb_g": "0.00",
        "satiety_index": 190,
        "common_unit": "1 cooked thigh = 95g",
        "notes": "Satiety score estimated for cooked poultry.",
    },
    {
        "name": "Lean beef mince, cooked",
        "kcal_per_100g": "217.00",
        "protein_g": "26.10",
        "fat_g": "11.80",
        "carb_g": "0.00",
        "satiety_index": 176,
        "common_unit": "1/2 cup cooked = 85g",
        "notes": "Macros estimated for cooked 90% lean beef mince. Satiety score estimated.",
    },
    {
        "name": "Kapenta, dried",
        "kcal_per_100g": "300.00",
        "protein_g": "60.00",
        "fat_g": "5.00",
        "carb_g": "0.00",
        "satiety_index": 225,
        "common_unit": "1 small handful = 30g",
        "notes": "Uses Holt fish satiety score. Macros vary by drying method.",
    },
    {
        "name": "River bream or tilapia, cooked",
        "kcal_per_100g": "128.00",
        "protein_g": "26.00",
        "fat_g": "2.70",
        "carb_g": "0.00",
        "satiety_index": 225,
        "common_unit": "1 fillet = 120g",
        "notes": "Uses Holt fish satiety score. Macros are for cooked tilapia/bream.",
    },
    {
        "name": "Canned tuna in water, drained",
        "kcal_per_100g": "116.00",
        "protein_g": "25.50",
        "fat_g": "0.80",
        "carb_g": "0.00",
        "satiety_index": 225,
        "common_unit": "1 drained can = 120g",
        "notes": "Uses Holt fish satiety score.",
    },
    {
        "name": "Whole egg",
        "kcal_per_100g": "143.00",
        "protein_g": "12.60",
        "fat_g": "9.50",
        "carb_g": "0.70",
        "satiety_index": 150,
        "common_unit": "1 large egg = 50g",
        "notes": "Holt satiety score for eggs.",
    },
    {
        "name": "Greek yoghurt, plain full-fat",
        "kcal_per_100g": "97.00",
        "protein_g": "9.00",
        "fat_g": "5.00",
        "carb_g": "3.90",
        "satiety_index": 160,
        "common_unit": "1 cup = 245g",
        "notes": "Macros vary by brand. Satiety score estimated for high-protein dairy.",
    },
    {
        "name": "Greek yoghurt, plain low-fat",
        "kcal_per_100g": "73.00",
        "protein_g": "10.00",
        "fat_g": "1.90",
        "carb_g": "3.90",
        "satiety_index": 170,
        "common_unit": "1 cup = 245g",
        "notes": "Macros vary by brand. Satiety score estimated for high-protein dairy.",
    },
    {
        "name": "Cottage cheese",
        "kcal_per_100g": "98.00",
        "protein_g": "11.10",
        "fat_g": "4.30",
        "carb_g": "3.40",
        "satiety_index": 165,
        "common_unit": "1/2 cup = 110g",
        "notes": "Macros vary by fat level. Satiety score estimated for high-protein dairy.",
    },
    {
        "name": "Firm tofu",
        "kcal_per_100g": "144.00",
        "protein_g": "17.30",
        "fat_g": "8.70",
        "carb_g": "2.80",
        "satiety_index": 150,
        "common_unit": "1/2 block = 150g",
        "notes": "Satiety score estimated for lean plant protein.",
    },
    {
        "name": "Peanut butter",
        "kcal_per_100g": "588.00",
        "protein_g": "25.10",
        "fat_g": "50.40",
        "carb_g": "20.00",
        "satiety_index": 90,
        "common_unit": "1 tablespoon = 16g",
        "notes": "Satiety score estimated lower because of high energy density.",
    },
    {
        "name": "Olive oil",
        "kcal_per_100g": "884.00",
        "protein_g": "0.00",
        "fat_g": "100.00",
        "carb_g": "0.00",
        "satiety_index": 40,
        "common_unit": "1 tablespoon = 14g",
        "notes": "Satiety score estimated for added fat.",
    },
    {
        "name": "Sesame oil",
        "kcal_per_100g": "884.00",
        "protein_g": "0.00",
        "fat_g": "100.00",
        "carb_g": "0.00",
        "satiety_index": 40,
        "common_unit": "1 tablespoon = 14g",
        "notes": "Satiety score estimated for added fat.",
    },
    {
        "name": "Apple, raw",
        "kcal_per_100g": "52.00",
        "protein_g": "0.30",
        "fat_g": "0.20",
        "carb_g": "13.80",
        "satiety_index": 197,
        "common_unit": "1 medium apple = 180g",
        "notes": "Holt satiety score for apples.",
    },
    {
        "name": "Banana, raw",
        "kcal_per_100g": "89.00",
        "protein_g": "1.10",
        "fat_g": "0.30",
        "carb_g": "22.80",
        "satiety_index": 118,
        "common_unit": "1 medium banana = 118g",
        "notes": "Satiety score estimated from fruit pattern.",
    },
    {
        "name": "Orange, raw",
        "kcal_per_100g": "47.00",
        "protein_g": "0.90",
        "fat_g": "0.10",
        "carb_g": "11.80",
        "satiety_index": 202,
        "common_unit": "1 medium orange = 130g",
        "notes": "Holt satiety score for oranges.",
    },
    {
        "name": "Mango, raw",
        "kcal_per_100g": "60.00",
        "protein_g": "0.80",
        "fat_g": "0.40",
        "carb_g": "15.00",
        "satiety_index": 140,
        "common_unit": "1 cup sliced = 165g",
        "notes": "Satiety score estimated for whole raw fruit.",
    },
    {
        "name": "Kale, cooked",
        "kcal_per_100g": "35.00",
        "protein_g": "2.90",
        "fat_g": "0.50",
        "carb_g": "4.40",
        "satiety_index": 180,
        "common_unit": "1 cup cooked = 130g",
        "notes": "Satiety score estimated for high-volume leafy vegetable.",
    },
    {
        "name": "Broccoli, cooked",
        "kcal_per_100g": "35.00",
        "protein_g": "2.40",
        "fat_g": "0.40",
        "carb_g": "7.20",
        "satiety_index": 180,
        "common_unit": "1 cup chopped = 156g",
        "notes": "Satiety score estimated for high-volume vegetable.",
    },
    {
        "name": "Bok choy, cooked",
        "kcal_per_100g": "12.00",
        "protein_g": "1.60",
        "fat_g": "0.20",
        "carb_g": "1.80",
        "satiety_index": 180,
        "common_unit": "1 cup cooked = 170g",
        "notes": "Satiety score estimated for high-volume leafy vegetable.",
    },
    {
        "name": "Cabbage, cooked",
        "kcal_per_100g": "23.00",
        "protein_g": "1.30",
        "fat_g": "0.10",
        "carb_g": "5.50",
        "satiety_index": 170,
        "common_unit": "1 cup cooked = 150g",
        "notes": "Satiety score estimated for high-volume vegetable.",
    },
    {
        "name": "Tomato, raw",
        "kcal_per_100g": "18.00",
        "protein_g": "0.90",
        "fat_g": "0.20",
        "carb_g": "3.90",
        "satiety_index": 150,
        "common_unit": "1 medium tomato = 120g",
        "notes": "Satiety score estimated for watery raw vegetable.",
    },
    {
        "name": "Onion, raw",
        "kcal_per_100g": "40.00",
        "protein_g": "1.10",
        "fat_g": "0.10",
        "carb_g": "9.30",
        "satiety_index": 130,
        "common_unit": "1 medium onion = 110g",
        "notes": "Satiety score estimated; usually logged as a recipe ingredient.",
    },
]


def seed_food_items(apps: Apps, _schema_editor: BaseDatabaseSchemaEditor) -> None:
    FoodItem = apps.get_model("tracker", "FoodItem")

    for food in FOOD_ITEMS:
        name = food["name"]
        defaults = {key: value for key, value in food.items() if key != "name"}
        FoodItem.objects.update_or_create(name=name, defaults=defaults)


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_fooditem_alter_weightentry_weight_kg_mealentry"),
    ]

    operations = [
        migrations.RunPython(seed_food_items, migrations.RunPython.noop),
    ]
