# Generated by Django 5.2.14 on 2026-05-12 13:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_seed_food_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=255)),
                ('morning_ping_time', models.TimeField(default=datetime.time(7, 0))),
                ('evening_ping_time', models.TimeField(default=datetime.time(21, 0))),
                ('weekly_summary_day', models.PositiveSmallIntegerField(default=6, help_text='0=Monday, 6=Sunday.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('weekly_summary_time', models.TimeField(default=datetime.time(19, 0))),
            ],
            options={
                'verbose_name': 'Telegram settings',
                'verbose_name_plural': 'Telegram settings',
            },
        ),
    ]
