# Generated by Django 5.2.14 on 2026-05-12 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_telegramsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="default_grams",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
