# Generated by Cursor on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0011_add_chinese_classics"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailylog",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
