# Generated by Django 5.2.14 on 2026-05-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_dailylog_closed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="source",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual entry"),
                    ("FDC", "USDA FoodData Central"),
                    ("OFF", "Open Food Facts"),
                ],
                default="MANUAL",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="source_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="source_url",
            field=models.URLField(blank=True),
        ),
    ]
